imports:
    - { resource: 'services.yml' }

parameters:
    module_settings:
        configuration:
            'VB_TEST_MODE' : 0
            'VB_API_KEY' : ''
            'VB_API_SECRET' : ''
            'VB_TAGS_SCRIPT' : ''
            'VB_LOGO_DISPLAY_IN_CHECKOUT' : 1
            'VB_ENABLE_ON_PRODUCT_PAGE' : 1
            'VB_ENABLE_ON_CART_SUMMARY' : 1
            'VB_ENABLE_ON_PAYMENT_SELECTION' : 1
            'VB_SINGLE_ACTION_CAPTURE_CONF' : 0
            'VB_BULK_ACTION_CAPTURE_CONF' : 0
            'VB_SINGLE_ACTION_REFUND_CONF' : 1
            'VB_BULK_ACTION_REFUND_CONF' : 1
            'VB_SINGLE_ACTION_CANCEL_CONF' : 1
            'VB_BULK_ACTION_CANCEL_CONF' : 1
            'VB_ENABLE_AUTO_PAYMENT_CAPTURE': 0
            'VB_CAPTURE_ORDER_STATUS_MULTI': '[]'
            'VB_PAYMENT_PENDING' : 0
            'VB_PAYMENT_ACCEPTED' : 0
            'VB_PAYMENT_COMPLETED' : 0
            'VB_PAYMENT_CANCELED' : 0
            'VB_PAYMENT_REFUNDED' : 0

        hooks:
            - 'moduleRoutes'
            - 'displayBeforeBodyClosingTag'
            - 'displayProductPriceBlock'
            - 'displayShoppingCart'
            - 'actionFrontControllerSetMedia'
            - 'actionAdminControllerSetMedia'
            - 'paymentOptions'
            - 'displayBackOfficeHeader'
            - 'displayExpressCheckout'
            - 'displayAdminOrder'
            - 'displayShoppingCartFooter'
            - 'displayShoppingCart'
            - 'displayOrderConfirmation'
            - 'displayHeader'
            - 'productActions'
            - 'payment'
            - 'actionOrderStatusUpdate'
            - 'actionOrderHistoryAddAfter'